eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
server:
    port: 8761
spring:
    application:
        name: eurekaserver
    config:
        import: optional:configserver:http://localhost:8071
    profiles:
        active: dev