server.port=8081
spring.application.name=Notification-service

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=consumer-notification-user-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.listenable-topics=user_create,user_delete

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

logging.file.name=logs/log.log
logging.level.org.springframework=OFF
logging.level.com.notificationservice=trace
logging.level.web=OFF
logging.logback.rollingpolicy.clean-history-on-start=true