spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=password
spring.data.jpa.repositories.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


logging.file.name=logs/log.log
logging.level.org.springframework=OFF
logging.level.com.userservice=trace
logging.level.sql=OFF
logging.level.web=OFF
logging.logback.rollingpolicy.clean-history-on-start=true