eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: eureka-server
    prefer-ip-address: false
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      userServiceCircuitBreaker:
        base-config: default
server:
    port: 8083
spring:
  cloud:
    client:
      hostname: gateway-api
    gateway.server.webflux:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE/
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/?(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user-service
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE/
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - RewritePath=/api/v1/users/?(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: notificationServiceCircuitBreaker
                fallbackUri: forward:/fallback/notification-service