eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
    instance:
        hostname: eureka-server
        prefer-ip-address: false
server:
    port: 8081
spring:
    cloud:
        client:
            hostname: notification-service
    kafka:
        consumer:
            auto-offset-reset: earliest
            bootstrap-servers: kafka:9092
            group-id: consumer-notification-user-group
            listenable-topics: user_create,user_delete
    mail:
        host: localhost
        port: 1025
        properties:
            mail:
                smtp:
                    auth: false
                    starttls:
                        enable: false
springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html